//MONGODB OPERATOR = POWERFULL

// LOGICAL OPERATOR

//$INC => INCREMENT
//$MIN => MINIMUM
//$MAX => MAXIMUM
//$SET => USED TO SET A DATA
//BOOK.TITLE = "XYZ"

//$UNSET => REMOVING A PROPERTY FROM AN OBJECT



//   ARRAY OPERATOR
//$PUSH
//NAME = ["DEEPESH","XYZ"]

//$POP = USED TO EXTRACT/REMOVE/DELETE THE LAST ELEMENT

//PULL
//PULL:{
//NAME: "XYZ"
//}

//#ADDTOSET => doesnot ALLOW DUPLICATES
